name: gqlens-docs
region: fra

domains:
  - domain: docs.gqlens.com
    type: PRIMARY

static_sites:
  - name: docs
    github:
      repo: Krister-Johansson/GQLens-docs
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: dist
